### ISSUE TITLE
PROD Test - Fields Not Populating

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#122]
The followingn fields are not populating in the widget and are populated in the database:

All Assets: Activity Tab
- Construction Purpose
- Status
- For Credit
- Office 

EFF_BMP and Outfall Stabilization (Assets and Site Selection): General Tab 
- Shop
- District 

EFF_BMP_RETROFIT & Outfall Stabilization (site selection): General Tab
- County
- District
- Shop

EFF_BMP: Inspection Tab
- Inspector 

Planting Trees: As Built Tab
- Status
- SHA Action

**Comment by TaraF** [comment]
This issue was happening on SHA Dev and KCI Dev as well.  There was a combination of webservices updates needed (Ehsan has fixed), and some Flex code issues. 

This is fixed, please wait to test until in SHA environment, and you have been notified.

**Comment by TaraF** [comment]
Available -- please test in SHA DEV:  http://shagbdapp/egis/viewer.html

**Comment by BrittanyHuber** [comment]
As-Built SHA Action is still not populating
planting trees > district 3 > 160087UT

**Comment by TaraF** [comment]
DB changes needed -- DB has description, when it should be showing the domain.  Please update DB (HISDEV_NEW) and test in http://shagbdapp/egis/viewer.html

**Comment by BrittanyHuber** [comment]
works in DEV ready for PROD

**Comment by BrittanyHuber** [comment]
works in PROD
