### ISSUE TITLE
PHASE II - KCI DEV - Versioning - 6.9 - stop editing does not disable

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#149]
When enabling an edit session within the versioning tab by selecting “start editing”, the system will display "stop editing." When attempting to end the edit session by selecting the "stop editing" button, the system prompts the user if they would like to save their edits or not. When the user selects “no” the system does end the editing session and the button remains "stop editing." When prompted to save edits, and the user selects “yes” the system stops the current editing session. 

To Recreate:
Create a version
in the versioning tab select the version you created
select "start editing"
select "stop editing"
when prompted to save edits, select "no"
the editing session remains active, and the button still displays "stop editing"

Select "stop editing" again 
when prompted to save edits select "yes"
the editing session is ended, and the button says "start editing"

**Comment by TaraF** [comment]
This has been fixed.  Please wait to test until notified.

**Comment by TaraF** [comment]
ready

**Comment by BrittanyHuber** [comment]
@TaraF I am still encountering this issue when attempting to end an edit session without saving edits. Error #2032 is returned and the system remains in an edit session.

**Comment by BrittanyHuber** [comment]
@TaraF When switching active editing sessions between two versions, the versioning tab appeared as if there were two active editing sessions at the same time.

![image](https://cloud.githubusercontent.com/assets/8092133/6759090/ccad75f6-cf13-11e4-8818-70fd159d714d.png)

To recreate:
Select one version in the versioning tab > start editing > stop editing
Switch versions in the upper right hand toggle to the same version you started editing > error #2032 
Select that same version in the versioning tab > start editing > stop editing 
Select a second version > start editing
Both will be in active editing sessions

When recreating this a second time, and both versions were left as active editing sessions and the browser was refreshed, upon opening the widget the Active edit session dialog box appears twice to allow me to stop editing for each version.

**Comment by TaraF** [comment]
NOTE:  this is happening when user switches "Select" in versioning tab, before properly stopping the first edit session.  This should not be allowed.

**Comment by TaraF** [comment]
Fixed. Version selection cannot be changed if there is an active edit session open (started).  System forces the user to stop the edit session first.

**Comment by BrittanyHuber** [comment]
verified that this is working in KCI DEV
