### ISSUE TITLE
PHASE II - KCI DEV - Advanced Query - 6.11.8 - doesn't return results

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#157]
The system does not return result when selecting features by advanced query. 

![image](https://cloud.githubusercontent.com/assets/8092133/6528224/8825eb6e-c3ee-11e4-8e59-92d81ea85903.png)

To Recreate:
TMDL Strategies > All TMDL Strategies
Field Name: ac.STATUS
Operator: =
Unique Value: CC (Construction Complete)
Add 
Does not validate

*this would return a decent amount of results - the system could be taking awhile for this query however, I was unable to successfully perform an advanced query and return results.

**Comment by BrittanyHuber** [comment]
@TaraF a few other examples:

TMDL Strategies > Swales > TMDL_BMP_TYPE = "N"
TMDL Strategies > Planting Trees > pay_item >= "4"

**Comment by TaraF** [comment]
Hi Ehsan,

This seems to be web service related -- this works when using FF, but not Chrome or IE.  I think it has to do with the return being able to read as XML, not just JSON.  I think you fixed a service like this for me in the past.  If needed, I can save a Fiddler session where this doesn't appear to be going through correctly. When you get back, can we take a look together?

Thanks

**Comment by TaraF** [comment]
This is resolved  (added in request: format=xml for FF and Chrome browsers).

Please wait to test until notified.

**Comment by TaraF** [comment]
ready

**Comment by BrittanyHuber** [comment]
@TaraF - still unable to return results for site selection features

**Comment by TaraF** [comment]
this was due to a time out issue -- too many results.  Results are now flagged -- if over 5000, the user is asked to narrow the results.  Please let me know if it continues -- if so i can lower the threashold.

please wait to test until notified.

**Comment by BrittanyHuber** [comment]
verified that this is working in KCI dev
