### ISSUE TITLE
PHASE III - KCI DEV - Error 2032 when adding Catch Basin Cleaning

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#201]
When attempting to add a catch basin cleaning asset, the system returns the IO error #2032

![image](https://cloud.githubusercontent.com/assets/8092133/7499545/62b23d28-f3f6-11e4-8025-98c4dff14b7b.png)

Also, the shop value is not maintained upon submitting the feature

![image](https://cloud.githubusercontent.com/assets/8092133/7499559/7ac549fa-f3f6-11e4-857e-f7536a369a1c.png)

Add > catch basin cleaning 
enter activity information
enter feature information
finish
IO error #2032 returned
Shop value is not populated

**Comment by GraceAi** [comment]
@ehsan67, there are duplicate MD_SHOP in LRInletCleaning.cs in web service, which causes SHOP field empty. Can you remove one?

**Comment by GraceAi** [comment]
@BrittanyHuber, what was your input for this error?

**Comment by BrittanyHuber** [comment]
@GraceAi - 
Add > catch basin cleaning 
entered activity information
entered feature information
finish
IO error #2032 returned
Shop value is not populated

**Comment by GraceAi** [comment]
@BrittanyHuber, what was the feature information did your enter?

**Comment by BrittanyHuber** [comment]
![image](https://cloud.githubusercontent.com/assets/8092133/7515793/1462cc44-f498-11e4-8619-6804b90b645b.png)
![image](https://cloud.githubusercontent.com/assets/8092133/7515806/2b2c5ecc-f498-11e4-866b-0f56470c688e.png)
![image](https://cloud.githubusercontent.com/assets/8092133/7515810/3505cd8e-f498-11e4-8e51-040be40ce1a9.png)

**Comment by ehsan67** [comment]
@GraceAi  md_shop fixed

**Comment by GraceAi** [comment]
@ehsan67,  INLET_SOLIDS, INLET_SOLID_DRYWEIGHT and TOTAL_DRY_WEIGHT are missing. Can you add them?

**Comment by ehsan67** [comment]
@GraceAi  added

**Comment by GraceAi** [comment]
Fixed. Need to update web service and flex.

**Comment by GraceAi** [comment]
@BrittanyHuber,  please retest. However, IO error #2032 persists because geometry retrieve failure. Existing CBCs also return this error. I believe it is data issue. 

@ehsan67, can you confirm it?

**Comment by BrittanyHuber** [comment]
tested in KCI DEV - able to add feature. @ehsan67 - error 2032 still persists due to data issue?

**Comment by BrittanyHuber** [comment]
fixed
