### ISSUE TITLE
PHASE III - KCI DEV - STRU_ID Numbering 

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#207]
When creating a new feature the system is generating a higher number but it is not the next consecutive number 

![image](https://cloud.githubusercontent.com/assets/8092133/7501638/8183518a-f403-11e4-9d36-1126caf7bad7.png)

Created a tree site in Harford county. The next consecutive number chosen was 121005UT. In the database the next consecutive number in Harford County is 120174UT.

**Comment by GraceAi** [comment]
@dhenry-KCI, isn't the SS_ID supposed to be globally unique? If it is unique in each county, two features in two different Counties may have the same SS_ID.

**Comment by dhenry-KCI** [comment]
@GraceAi , In the SS_ID, the first two numbers determine the County and the next four the SS_ID.So the four digit number only needs to be unique within each County.

**Comment by ehsan67** [comment]
Please test again

**Comment by BrittanyHuber** [comment]
@ehsan67 - wetlands and pavement removal are not populating with a number or a code. Also, it seems that the number being populated is not the next highest number available in the selected county. The number being populated starts with 1000. 

![image](https://cloud.githubusercontent.com/assets/8092133/7746952/8b9adef4-ff84-11e4-8478-45d09e2b82a3.png)

**Comment by ehsan67** [comment]
@BrittanyHuber  sorry I forgot to tell you , I reset the number, so it is normal to see it starts form 1000. Each Strategy Group (for example : Stream Restoration, Outfall, StreetSweeping and etc.) has its own counter which starts from 1000 and goes up.

I believe I fixed wetlands, is "IUSR" the strategy type for PavementRemoval?

**Comment by GraceAi** [comment]
@ehsan67, PavementRemoval's strategy type is IMPP.

**Comment by ehsan67** [comment]
@BrittanyHuber  what are the letters that I need to append to the generated Stru number for IMPP ?

**Comment by BrittanyHuber** [comment]
@ehsan67 - sounds great! so it is working then. pavement removal is "UI"

**Comment by ehsan67** [comment]
fixed

**Comment by BrittanyHuber** [comment]
@ehsan67 - pavement is now working but wetlands are still not populating with a number and code (code = AW)

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and verified that this is working
