### ISSUE TITLE
Tree Inspections (TMDL Widget) 6.36.1 Tree inspection disappears

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#76]
6.36.1
When toggling between inspections when a tree has more than one inspection, the fields and data disappears

-Filter by Trees in Baltimore County
-Select facility 030072UT
-Click on Inspections
-Toggle to inspection on 4/25/2013
-Everything disappears

![untitled6](https://cloud.githubusercontent.com/assets/7804977/3528520/3561e81c-0790-11e4-88e4-7f68e164a933.jpg)

![untitled7](https://cloud.githubusercontent.com/assets/7804977/3528523/37e4693e-0790-11e4-8993-b73fa776dd22.jpg)

**Comment by ecomwu** [comment]
I've fixed this issue and committed the changes. Please test it later.

**Comment by dhenry-KCI** [comment]
Maggie- I am still seeing this issue. to recreate-
Filter by TMDL Strategies > Planting Trees or Forestation on Pervious Urban
County = Baltimore
TDML ID = 030038UT

This record has two inspections. The first inspection appears correctly, the second one does not.

**Comment by ecomwu** [comment]
This is fixed. I haven't considered the asset type while changing the inspection date selection, that caused issue.

I've committed the changes.
